services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: crosswave
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: crosswave
    ports:
      - "27017:27017"

  auth:
    build:
      context: .
      dockerfile: ./crosswave-auth/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      CROSSWAVE_MONGODB_CONNECTIONSTRING: "mongodb://crosswave:12345678@mongo:27017/admin"

  music:
    build:
      context: .
      dockerfile: ./crosswave-music/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mongo
    environment:
      CROSSWAVE_AUTH_API_BASEURL: "http://auth:8080"