openapi: 3.0.0
info:
  title: Crosswave Analytics
  description: Crosswave Analytics and profiles service
  version: 0.0.1
servers:
  - url: 'localhost:8080'
paths:
  /profile/v1/get:
    $ref: "./endpoints/get-profile.yaml"

  /profile/v1/update:
    $ref: "./endpoints/update-profile.yaml"

  /profile/v1/like:
    $ref: "./endpoints/like-track.yaml"

  /profile/v1/dislike:
    $ref: "./endpoints/dislike-track.yaml"

  /profile/v1/subscribe:
    $ref: "./endpoints/subscribe.yaml"

  /profile/v1/unsubscribe:
    $ref: "./endpoints/unsubscribe.yaml"
